# Generated by Django 2.2.11 on 2020-05-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaterie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='make_public',
            field=models.BooleanField(default=False),
        ),
    ]
