# Generated by Django 2.2.11 on 2020-03-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eaterie', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
    ]
