# Generated by Django 2.2.11 on 2020-03-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaterie', '0002_auto_20200322_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_file',
            field=models.ImageField(blank=True, default='no-image-available.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_file',
            field=models.ImageField(blank=True, default='no-image-available.png', upload_to=''),
        ),
    ]
