# Generated by Django 2.2.11 on 2020-03-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaterie', '0003_auto_20200323_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preference1',
            field=models.CharField(choices=[('ITA', 'Italian'), ('FF', 'Fastfood'), ('CHN', 'Chinese'), ('VTN', 'Vietnamese')], default='ITA', max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='preference2',
            field=models.CharField(choices=[('ITA', 'Italian'), ('FF', 'Fastfood'), ('CHN', 'Chinese'), ('VTN', 'Vietnamese')], default='VTN', max_length=64),
        ),
    ]
