# Generated by Django 2.2.11 on 2020-04-24 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eaterie', '0003_auto_20200423_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='eaterie.Order'),
        ),
    ]
