# Generated by Django 2.2.11 on 2020-03-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eaterie', '0004_auto_20200327_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='preference1',
            new_name='preference_1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='preference2',
            new_name='preference_2',
        ),
    ]
